user                            www;
worker_processes                auto;

error_log                       /var/log/nginx/error.log warn;

events {
    worker_connections          1024;
}

http {
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    on;
    access_log                  /var/log/nginx/access.log;
    error_log                   /var/log/nginx/quic.log info;
    keepalive_timeout           3000;

    quic_gso                    on;

    server {
        listen                  80;
        listen                  443 quic reuseport;
        listen                  443 ssl;

        ssl_certificate         /var/ssl/certificate.crt;
        ssl_certificate_key     /var/ssl/privatekey.key;
        root                    /var/www;
        index                   index.html index.htm;
        server_name             pds-server;
        client_max_body_size    32m;
        error_page              500 502 503 504  /50x.html;
        location = /50x.html {
              root              /var/lib/nginx/html;
        }
        location / {
              create_full_put_path  on;
              dav_methods           PUT;
              dav_access            group:rw all:rw;
        }
    }
}
